### ISSUE TITLE
2nd midi port

### ISSUE THREAD

**Issue by ZXMicroJack** [rppicomidi/midi2usbdev#1]
Hi.  I've taken a local copy of this repo and added a 2nd midi port on uart 0.  I'm using it for the last two days and seems to work well - I can create a PR with the changes if you wish?

Cheers, MJ.

**Comment by rppicomidi** [comment]
I already have a project that supports USB Device and more than one MIDI port. See [midi-multistream2usbdev](https://github.com/rppicomidi/midi-multistream2usbdev). The intent of this project is to be very simple. What does your pull request bring that [midi-multistream2usbdev](https://github.com/rppicomidi/midi-multistream2usbdev) does not? Of course, you may always submit a pull request and I will review it.

**Comment by ZXMicroJack** [comment]
I had not seen that.  I only offered to share with you my simple modification.  The multistream project seems to me a bit overkill for my needs.   Anyway i have many projects on the go at the moment, I'll just take a fork and leave it at that.   Thanks for sharing your project.  Have a nice day.
